services:
  docs:
    networks: [markschron]
    build:
      context: .
      dockerfile: Dockerfile
    image: markschron-docs
    container_name: docs
    restart: unless-stopped
    ports:
      - '4173:80'

networks:
  markschron:
